import { MigrationInterface, QueryRunner } from "typeorm";

export class AddLocationIdToCourseSessions1762352642974 implements MigrationInterface {
    name = 'AddLocationIdToCourseSessions1762352642974'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "location" DROP CONSTRAINT "fk_location_tenant"`);
        await queryRunner.query(`ALTER TABLE "course" DROP CONSTRAINT "FK_COURSE_TENANT"`);
        await queryRunner.query(`ALTER TABLE "course_session" DROP CONSTRAINT "FK_SESSION_TENANT"`);
        await queryRunner.query(`ALTER TABLE "course_session" DROP CONSTRAINT "FK_SESSION_COURSE"`);
        await queryRunner.query(`ALTER TABLE "enrollment" DROP CONSTRAINT "FK_ENROLLMENT_TENANT"`);
        await queryRunner.query(`ALTER TABLE "enrollment" DROP CONSTRAINT "FK_ENROLLMENT_STUDENT"`);
        await queryRunner.query(`ALTER TABLE "enrollment" DROP CONSTRAINT "FK_ENROLLMENT_COURSE"`);
        await queryRunner.query(`ALTER TABLE "enrollment" DROP CONSTRAINT "FK_ENROLLMENT_SESSION"`);
        await queryRunner.query(`ALTER TABLE "enrollment" DROP CONSTRAINT "FK_ENROLLMENT_ENROLLED_BY"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_COURSE_TENANT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_COURSE_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_COURSE_CATEGORY"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_COURSE_FEATURED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SESSION_TENANT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SESSION_COURSE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SESSION_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SESSION_START_DATE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SESSION_END_DATE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SESSION_REGISTRATION_OPEN"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ENROLLMENT_COURSE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ENROLLMENT_SESSION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ENROLLMENT_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ENROLLMENT_PAYMENT_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ENROLLMENT_STUDENT_SESSION"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ENROLLMENT_CERTIFICATE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ENROLLMENT_TENANT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ENROLLMENT_STUDENT"`);
        await queryRunner.query(`DROP INDEX "public"."idx_role_permission_unique"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_role_unique"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "PK_96c8f1fd25538d3692024115b47"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "PK_fb2e442d14add3cefbdf33c4561"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP COLUMN "assigned_at"`);
        await queryRunner.query(`ALTER TABLE "course_session" ADD "location_id" uuid`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "PK_19a94c31d4960ded0dcd0397759" PRIMARY KEY ("role_id", "permission_id")`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "PK_f634684acb47c1a158b83af5150" PRIMARY KEY ("user_id", "role_id")`);
        await queryRunner.query(`ALTER TYPE "public"."subscription_plan_enum" RENAME TO "subscription_plan_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."tenant_subscription_plan_enum" AS ENUM('starter', 'professional', 'enterprise')`);
        await queryRunner.query(`ALTER TABLE "tenant" ALTER COLUMN "subscription_plan" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant" ALTER COLUMN "subscription_plan" TYPE "public"."tenant_subscription_plan_enum" USING "subscription_plan"::"text"::"public"."tenant_subscription_plan_enum"`);
        await queryRunner.query(`ALTER TABLE "tenant" ALTER COLUMN "subscription_plan" SET DEFAULT 'starter'`);
        await queryRunner.query(`DROP TYPE "public"."subscription_plan_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."subscription_status_enum" RENAME TO "subscription_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."tenant_subscription_status_enum" AS ENUM('trial', 'active', 'suspended', 'cancelled', 'expired')`);
        await queryRunner.query(`ALTER TABLE "tenant" ALTER COLUMN "subscription_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant" ALTER COLUMN "subscription_status" TYPE "public"."tenant_subscription_status_enum" USING "subscription_status"::"text"::"public"."tenant_subscription_status_enum"`);
        await queryRunner.query(`ALTER TABLE "tenant" ALTER COLUMN "subscription_status" SET DEFAULT 'trial'`);
        await queryRunner.query(`DROP TYPE "public"."subscription_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "tenant" ALTER COLUMN "settings" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "location" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "location" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."course_status_enum" RENAME TO "course_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."course_course_status_enum" AS ENUM('draft', 'published', 'archived')`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "course_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "course_status" TYPE "public"."course_course_status_enum" USING "course_status"::"text"::"public"."course_course_status_enum"`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "course_status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."course_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."course_level_enum" RENAME TO "course_level_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."course_course_level_enum" AS ENUM('beginner', 'intermediate', 'advanced', 'all_levels')`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "course_level" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "course_level" TYPE "public"."course_course_level_enum" USING "course_level"::"text"::"public"."course_course_level_enum"`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "course_level" SET DEFAULT 'all_levels'`);
        await queryRunner.query(`DROP TYPE "public"."course_level_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."session_status_enum" RENAME TO "session_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."course_session_session_status_enum" AS ENUM('scheduled', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "course_session" ALTER COLUMN "session_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "course_session" ALTER COLUMN "session_status" TYPE "public"."course_session_session_status_enum" USING "session_status"::"text"::"public"."course_session_session_status_enum"`);
        await queryRunner.query(`ALTER TABLE "course_session" ALTER COLUMN "session_status" SET DEFAULT 'scheduled'`);
        await queryRunner.query(`DROP TYPE "public"."session_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."session_type_enum" RENAME TO "session_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."course_session_session_type_enum" AS ENUM('online', 'in_person', 'hybrid')`);
        await queryRunner.query(`ALTER TABLE "course_session" ALTER COLUMN "session_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "course_session" ALTER COLUMN "session_type" TYPE "public"."course_session_session_type_enum" USING "session_type"::"text"::"public"."course_session_session_type_enum"`);
        await queryRunner.query(`ALTER TABLE "course_session" ALTER COLUMN "session_type" SET DEFAULT 'in_person'`);
        await queryRunner.query(`DROP TYPE "public"."session_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."enrollment_status_enum" RENAME TO "enrollment_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."enrollment_enrollment_status_enum" AS ENUM('pending', 'confirmed', 'cancelled', 'completed', 'no_show')`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "enrollment_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "enrollment_status" TYPE "public"."enrollment_enrollment_status_enum" USING "enrollment_status"::"text"::"public"."enrollment_enrollment_status_enum"`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "enrollment_status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."enrollment_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_status_enum" RENAME TO "payment_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."enrollment_payment_status_enum" AS ENUM('unpaid', 'partial', 'paid', 'refunded', 'waived')`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "payment_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "payment_status" TYPE "public"."enrollment_payment_status_enum" USING "payment_status"::"text"::"public"."enrollment_payment_status_enum"`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "payment_status" SET DEFAULT 'unpaid'`);
        await queryRunner.query(`DROP TYPE "public"."payment_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."attendance_status_enum" RENAME TO "attendance_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."enrollment_attendance_status_enum" AS ENUM('not_started', 'present', 'absent', 'partial')`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "attendance_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "attendance_status" TYPE "public"."enrollment_attendance_status_enum" USING "attendance_status"::"text"::"public"."enrollment_attendance_status_enum"`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "attendance_status" SET DEFAULT 'not_started'`);
        await queryRunner.query(`DROP TYPE "public"."attendance_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "enrolled_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_3d0a7155eafd75ddba5a701336" ON "role_permission" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3a3ba47b7ca00fd23be4ebd6c" ON "role_permission" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d0e5815877f7395a198a4cb0a4" ON "user_role" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_32a6fc2fcb019d8e3a8ace0f55" ON "user_role" ("role_id") `);
        await queryRunner.query(`ALTER TABLE "course" ADD CONSTRAINT "FK_436db49b44a433f2a64210ee503" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_session" ADD CONSTRAINT "FK_feeec44db30078dfcff6901274d" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_session" ADD CONSTRAINT "FK_7d09aa9b1873078d3eae312b69b" FOREIGN KEY ("course_id") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_session" ADD CONSTRAINT "FK_d4a0eba434a58fcb0801da389ab" FOREIGN KEY ("location_id") REFERENCES "location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollment" ADD CONSTRAINT "FK_3513b9a5a02af5a4eb722460302" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollment" ADD CONSTRAINT "FK_eb0d79d7b8954d3129d032b0bb1" FOREIGN KEY ("student_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollment" ADD CONSTRAINT "FK_dd1ce01d1164c8bbdda052ced74" FOREIGN KEY ("course_id") REFERENCES "course"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollment" ADD CONSTRAINT "FK_12398d594a0d963a36f757dc36f" FOREIGN KEY ("session_id") REFERENCES "course_session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollment" ADD CONSTRAINT "FK_a6245adc129aa145954b9c3b667" FOREIGN KEY ("enrolled_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf" FOREIGN KEY ("permission_id") REFERENCES "permission"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368"`);
        await queryRunner.query(`ALTER TABLE "enrollment" DROP CONSTRAINT "FK_a6245adc129aa145954b9c3b667"`);
        await queryRunner.query(`ALTER TABLE "enrollment" DROP CONSTRAINT "FK_12398d594a0d963a36f757dc36f"`);
        await queryRunner.query(`ALTER TABLE "enrollment" DROP CONSTRAINT "FK_dd1ce01d1164c8bbdda052ced74"`);
        await queryRunner.query(`ALTER TABLE "enrollment" DROP CONSTRAINT "FK_eb0d79d7b8954d3129d032b0bb1"`);
        await queryRunner.query(`ALTER TABLE "enrollment" DROP CONSTRAINT "FK_3513b9a5a02af5a4eb722460302"`);
        await queryRunner.query(`ALTER TABLE "course_session" DROP CONSTRAINT "FK_d4a0eba434a58fcb0801da389ab"`);
        await queryRunner.query(`ALTER TABLE "course_session" DROP CONSTRAINT "FK_7d09aa9b1873078d3eae312b69b"`);
        await queryRunner.query(`ALTER TABLE "course_session" DROP CONSTRAINT "FK_feeec44db30078dfcff6901274d"`);
        await queryRunner.query(`ALTER TABLE "course" DROP CONSTRAINT "FK_436db49b44a433f2a64210ee503"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32a6fc2fcb019d8e3a8ace0f55"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0e5815877f7395a198a4cb0a4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3a3ba47b7ca00fd23be4ebd6c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d0a7155eafd75ddba5a701336"`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "enrolled_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_status_enum_old" AS ENUM('not_started', 'present', 'absent', 'partial')`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "attendance_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "attendance_status" TYPE "public"."attendance_status_enum_old" USING "attendance_status"::"text"::"public"."attendance_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "attendance_status" SET DEFAULT 'not_started'`);
        await queryRunner.query(`DROP TYPE "public"."enrollment_attendance_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."attendance_status_enum_old" RENAME TO "attendance_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."payment_status_enum_old" AS ENUM('unpaid', 'partial', 'paid', 'refunded', 'waived')`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "payment_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "payment_status" TYPE "public"."payment_status_enum_old" USING "payment_status"::"text"::"public"."payment_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "payment_status" SET DEFAULT 'unpaid'`);
        await queryRunner.query(`DROP TYPE "public"."enrollment_payment_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_status_enum_old" RENAME TO "payment_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."enrollment_status_enum_old" AS ENUM('pending', 'confirmed', 'cancelled', 'completed', 'no_show')`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "enrollment_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "enrollment_status" TYPE "public"."enrollment_status_enum_old" USING "enrollment_status"::"text"::"public"."enrollment_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "enrollment" ALTER COLUMN "enrollment_status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."enrollment_enrollment_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."enrollment_status_enum_old" RENAME TO "enrollment_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."session_type_enum_old" AS ENUM('online', 'in_person', 'hybrid')`);
        await queryRunner.query(`ALTER TABLE "course_session" ALTER COLUMN "session_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "course_session" ALTER COLUMN "session_type" TYPE "public"."session_type_enum_old" USING "session_type"::"text"::"public"."session_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "course_session" ALTER COLUMN "session_type" SET DEFAULT 'in_person'`);
        await queryRunner.query(`DROP TYPE "public"."course_session_session_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."session_type_enum_old" RENAME TO "session_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."session_status_enum_old" AS ENUM('scheduled', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "course_session" ALTER COLUMN "session_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "course_session" ALTER COLUMN "session_status" TYPE "public"."session_status_enum_old" USING "session_status"::"text"::"public"."session_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "course_session" ALTER COLUMN "session_status" SET DEFAULT 'scheduled'`);
        await queryRunner.query(`DROP TYPE "public"."course_session_session_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."session_status_enum_old" RENAME TO "session_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."course_level_enum_old" AS ENUM('beginner', 'intermediate', 'advanced', 'all_levels')`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "course_level" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "course_level" TYPE "public"."course_level_enum_old" USING "course_level"::"text"::"public"."course_level_enum_old"`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "course_level" SET DEFAULT 'all_levels'`);
        await queryRunner.query(`DROP TYPE "public"."course_course_level_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."course_level_enum_old" RENAME TO "course_level_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."course_status_enum_old" AS ENUM('draft', 'published', 'archived')`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "course_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "course_status" TYPE "public"."course_status_enum_old" USING "course_status"::"text"::"public"."course_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "course_status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."course_course_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."course_status_enum_old" RENAME TO "course_status_enum"`);
        await queryRunner.query(`ALTER TABLE "location" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "location" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tenant" ALTER COLUMN "settings" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_status_enum_old" AS ENUM('trial', 'active', 'suspended', 'cancelled', 'expired')`);
        await queryRunner.query(`ALTER TABLE "tenant" ALTER COLUMN "subscription_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant" ALTER COLUMN "subscription_status" TYPE "public"."subscription_status_enum_old" USING "subscription_status"::"text"::"public"."subscription_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "tenant" ALTER COLUMN "subscription_status" SET DEFAULT 'trial'`);
        await queryRunner.query(`DROP TYPE "public"."tenant_subscription_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."subscription_status_enum_old" RENAME TO "subscription_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_plan_enum_old" AS ENUM('starter', 'professional', 'enterprise')`);
        await queryRunner.query(`ALTER TABLE "tenant" ALTER COLUMN "subscription_plan" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant" ALTER COLUMN "subscription_plan" TYPE "public"."subscription_plan_enum_old" USING "subscription_plan"::"text"::"public"."subscription_plan_enum_old"`);
        await queryRunner.query(`ALTER TABLE "tenant" ALTER COLUMN "subscription_plan" SET DEFAULT 'starter'`);
        await queryRunner.query(`DROP TYPE "public"."tenant_subscription_plan_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."subscription_plan_enum_old" RENAME TO "subscription_plan_enum"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "PK_f634684acb47c1a158b83af5150"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "PK_19a94c31d4960ded0dcd0397759"`);
        await queryRunner.query(`ALTER TABLE "course_session" DROP COLUMN "location_id"`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD "assigned_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "PK_fb2e442d14add3cefbdf33c4561" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "PK_96c8f1fd25538d3692024115b47" PRIMARY KEY ("id")`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_user_role_unique" ON "user_role" ("user_id", "role_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_role_permission_unique" ON "role_permission" ("role_id", "permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ENROLLMENT_STUDENT" ON "enrollment" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ENROLLMENT_TENANT" ON "enrollment" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ENROLLMENT_CERTIFICATE" ON "enrollment" ("certificate_issued") `);
        await queryRunner.query(`CREATE INDEX "IDX_ENROLLMENT_STUDENT_SESSION" ON "enrollment" ("student_id", "session_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ENROLLMENT_PAYMENT_STATUS" ON "enrollment" ("payment_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ENROLLMENT_STATUS" ON "enrollment" ("enrollment_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ENROLLMENT_SESSION" ON "enrollment" ("session_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ENROLLMENT_COURSE" ON "enrollment" ("course_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_SESSION_REGISTRATION_OPEN" ON "course_session" ("is_registration_open") `);
        await queryRunner.query(`CREATE INDEX "IDX_SESSION_END_DATE" ON "course_session" ("end_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_SESSION_START_DATE" ON "course_session" ("start_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_SESSION_STATUS" ON "course_session" ("session_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_SESSION_COURSE" ON "course_session" ("course_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_SESSION_TENANT" ON "course_session" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_COURSE_FEATURED" ON "course" ("is_featured") `);
        await queryRunner.query(`CREATE INDEX "IDX_COURSE_CATEGORY" ON "course" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_COURSE_STATUS" ON "course" ("course_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_COURSE_TENANT" ON "course" ("tenant_id") `);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf" FOREIGN KEY ("permission_id") REFERENCES "permission"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollment" ADD CONSTRAINT "FK_ENROLLMENT_ENROLLED_BY" FOREIGN KEY ("enrolled_by") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollment" ADD CONSTRAINT "FK_ENROLLMENT_SESSION" FOREIGN KEY ("session_id") REFERENCES "course_session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollment" ADD CONSTRAINT "FK_ENROLLMENT_COURSE" FOREIGN KEY ("course_id") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollment" ADD CONSTRAINT "FK_ENROLLMENT_STUDENT" FOREIGN KEY ("student_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollment" ADD CONSTRAINT "FK_ENROLLMENT_TENANT" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_session" ADD CONSTRAINT "FK_SESSION_COURSE" FOREIGN KEY ("course_id") REFERENCES "course"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_session" ADD CONSTRAINT "FK_SESSION_TENANT" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course" ADD CONSTRAINT "FK_COURSE_TENANT" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location" ADD CONSTRAINT "fk_location_tenant" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
